2014/09/03 07:00:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "home ".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/
---
2014/09/03 07:00:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/
---
2014/09/03 07:33:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:33:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:33:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:34:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:34:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:38:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:51:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:51:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:51:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:51:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:51:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 07:52:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 08:08:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/login
---
2014/09/03 08:09:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 08:09:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 08:11:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
---
2014/09/03 08:11:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in /var/www/acc/yiicore/framework/web/CController.php:483
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CController.php(270): CController->missingAction('user')
#1 /var/www/acc/yiicore/framework/web/CWebApplication.php(282): CController->run('user')
#2 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('user/user/login')
#3 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/acc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/acc/index.php/user/user/login
---
2014/09/03 08:21:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
HTTP_REFERER=http://127.0.0.1/acc/index/login
---
2014/09/03 08:23:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
HTTP_REFERER=http://127.0.0.1/acc/index/login
---
2014/09/03 08:23:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/login".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/login
HTTP_REFERER=http://127.0.0.1/acc/index/login
---
2014/09/03 08:24:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/logout".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/logout')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/index.php/site/logout
HTTP_REFERER=http://127.0.0.1/acc/index.php/index/login
---
2014/09/03 08:40:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in /var/www/acc/yiicore/framework/web/CController.php:483
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CController.php(270): CController->missingAction('user')
#1 /var/www/acc/yiicore/framework/web/CWebApplication.php(282): CController->run('user')
#2 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('index/user/inde...')
#3 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/acc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/acc/index.php/index/user/index
---
2014/09/03 08:42:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in /var/www/acc/yiicore/framework/web/CController.php:483
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CController.php(270): CController->missingAction('user')
#1 /var/www/acc/yiicore/framework/web/CWebApplication.php(282): CController->run('user')
#2 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('index/user/inde...')
#3 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/acc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/acc/index/user/index
---
2014/09/03 09:10:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site/logout".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('site/logout')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/site/logout
HTTP_REFERER=http://127.0.0.1/acc/user
---
2014/09/03 09:23:12 [error] [exception.CException] exception 'CException' with message 'Property "User.score" is not defined.' in /var/www/acc/yiicore/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/acc/yiicore/framework/db/ar/CActiveRecord.php(145): CComponent->__get('score')
#1 /var/www/acc/yiicore/framework/base/CComponent.php(612) : eval()'d code(1): CActiveRecord->__get('score')
#2 /var/www/acc/yiicore/framework/base/CComponent.php(612): eval()
#3 /var/www/acc/yiicore/framework/zii/widgets/grid/CButtonColumn.php(337): CComponent->evaluateExpression('$data->score > ...', Array)
#4 /var/www/acc/yiicore/framework/zii/widgets/grid/CButtonColumn.php(319): CButtonColumn->renderButton('down', Array, 0, Object(User))
#5 /var/www/acc/yiicore/framework/zii/widgets/grid/CGridColumn.php(151): CButtonColumn->renderDataCellContent(0, Object(User))
#6 /var/www/acc/yiicore/framework/zii/widgets/grid/CGridView.php(616): CGridColumn->renderDataCell(0)
#7 /var/www/acc/yiicore/framework/zii/widgets/grid/CGridView.php(572): CGridView->renderTableRow(0)
#8 /var/www/acc/yiicore/framework/zii/widgets/grid/CGridView.php(482): CGridView->renderTableBody()
#9 /var/www/acc/yiicore/framework/zii/widgets/CBaseListView.php(167): CGridView->renderItems()
#10 [internal function]: CBaseListView->renderSection(Array)
#11 /var/www/acc/yiicore/framework/zii/widgets/CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{item...')
#12 /var/www/acc/yiicore/framework/zii/widgets/CBaseListView.php(135): CBaseListView->renderContent()
#13 /var/www/acc/yiicore/framework/web/CBaseController.php(173): CBaseListView->run()
#14 /var/www/acc/protected/views/user/admin.php(74): CBaseController->widget('zii.widgets.gri...', Array)
#15 /var/www/acc/yiicore/framework/web/CBaseController.php(126): require('/var/www/acc/pr...')
#16 /var/www/acc/yiicore/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/acc/pr...', Array, true)
#17 /var/www/acc/yiicore/framework/web/CController.php(869): CBaseController->renderFile('/var/www/acc/pr...', Array, true)
#18 /var/www/acc/yiicore/framework/web/CController.php(782): CController->renderPartial('admin', Array, true)
#19 /var/www/acc/protected/controllers/UserController.php(143): CController->render('admin', Array)
#20 /var/www/acc/yiicore/framework/web/actions/CInlineAction.php(49): UserController->actionAdmin()
#21 /var/www/acc/yiicore/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#22 /var/www/acc/yiicore/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#23 /var/www/acc/yiicore/framework/web/filters/CFilter.php(40): CFilterChain->run()
#24 /var/www/acc/yiicore/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#25 /var/www/acc/yiicore/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#26 /var/www/acc/yiicore/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#27 /var/www/acc/yiicore/framework/web/CController.php(291): CFilterChain->run()
#28 /var/www/acc/yiicore/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#29 /var/www/acc/yiicore/framework/web/CWebApplication.php(282): CController->run('admin')
#30 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#31 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#32 /var/www/acc/index.php(13): CApplication->run()
#33 {main}
REQUEST_URI=/acc/user/admin
HTTP_REFERER=http://127.0.0.1/acc/user/index
---
2014/09/03 09:23:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/email.png".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('images/email.pn...')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/images/email.png
HTTP_REFERER=http://127.0.0.1/acc/user/admin
---
2014/09/03 09:24:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/email.png".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('images/email.pn...')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/images/email.png
HTTP_REFERER=http://127.0.0.1/acc/user/admin
---
2014/09/03 09:24:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "invoice/add".' in /var/www/acc/yiicore/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/acc/yiicore/framework/web/CWebApplication.php(141): CWebApplication->runController('invoice/add')
#1 /var/www/acc/yiicore/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/acc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/acc/invoice/add
HTTP_REFERER=http://127.0.0.1/acc/user/admin
---
